In [2]:
!pip install -U transformers datasets accelerate evaluate

Collecting transformers
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.3)
Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.8.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.24.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.4.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 69.6 MB/s eta 0:00:00:00:01:01
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 32.5 MB/s eta 0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 28.7 MB/s eta 0:00:00
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.9 MB/s eta 0:00:00
Downloading huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 625.2/625.2 kB 37.8 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 77.5 MB/s eta 0:00:00:00:01
Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 93.1 MB/s eta 0:00:00:00:01
Installing collected packages: hf-xet, huggingface-hub, tokenizers, datasets, accelerate, transformers, evaluate
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.3.0
    Uninstalling hf-xet-1.3.0:
      Successfully uninstalled hf-xet-1.3.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.8.3
    Uninstalling datasets-4.8.3:
      Successfully uninstalled datasets-4.8.3
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.12.0
    Uninstalling accelerate-1.12.0:
      Successfully uninstalled accelerate-1.12.0
Successfully installed accelerate-1.13.0 datasets-4.8.4 evaluate-0.4.6 hf-xet-1.4.2 huggingface-hub-1.8.0 tokenizers-0.22.2 transformers-5.4.0

In [3]:
!pip install librosa soundfile audiomentations -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.1/86.1 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.4/109.4 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.5/248.5 kB 10.9 MB/s eta 0:00:00

In [5]:
import os
import numpy as np
import pandas as pd
import librosa
import soundfile as sf
from pathlib import Path
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

BASE = Path("/kaggle/working/ser-india")
RAW  = BASE / "data/raw"
PROC = BASE / "data/processed"

for p in [RAW/"shemo", RAW/"iiith", PROC]:
    p.mkdir(parents=True, exist_ok=True)

print("Folders ready")

Folders ready

In [6]:
SHEMO = RAW / "shemo_repo"
SHEMO.mkdir(parents=True, exist_ok=True)

print("Shemo folder created at:", SHEMO)

Shemo folder created at: /kaggle/working/ser-india/data/raw/shemo_repo

In [7]:
import shutil
from pathlib import Path

src_paths = [
    Path("/kaggle/input/datasets/apoorv007/shemorepo/female"),
    Path("/kaggle/input/datasets/apoorv007/shemorepo/male")
]

# Copy folders
for src in src_paths:
    dst = SHEMO / src.name
    shutil.copytree(src, dst, dirs_exist_ok=True)

print("Files copied to:", SHEMO)

Files copied to: /kaggle/working/ser-india/data/raw/shemo_repo

In [8]:
shemo_repo = RAW / "shemo_repo"
wav_files = list(shemo_repo.rglob("*.wav"))
print(f"Total WAV files found: {len(wav_files)}")
print("\nSample filenames:")
for f in wav_files[:8]:
    print(f"  {f.name}  →  parent: {f.parent.name}")

Total WAV files found: 3000

Sample filenames:
  M02A27.wav  →  parent: male
  M51N10.wav  →  parent: male
  M37N14.wav  →  parent: male
  M34H03.wav  →  parent: male
  M02N10.wav  →  parent: male
  M20N08.wav  →  parent: male
  M18N14.wav  →  parent: male
  M43A10.wav  →  parent: male

In [9]:
import pandas as pd
from pathlib import Path

data = []

for file in wav_files:
    filename = file.name
    
    # Extract emotion code (example: N, H, A, S, F, D)
    emotion_code = filename[3]  # check this based on your dataset
    
    data.append({
        "path": str(file),
        "emotion": emotion_code
    })

df = pd.DataFrame(data)
df.head()

                                                path emotion
0  /kaggle/working/ser-india/data/raw/shemo_repo/...       A
1  /kaggle/working/ser-india/data/raw/shemo_repo/...       N
2  /kaggle/working/ser-india/data/raw/shemo_repo/...       N
3  /kaggle/working/ser-india/data/raw/shemo_repo/...       H
4  /kaggle/working/ser-india/data/raw/shemo_repo/...       N

Arrowhead DOES NOT care about:

happiness
disgust
Map to business classes:

In [10]:
mapping = {
    'A': 'frustrated',   # anger
    'N': 'calm',         # neutral
    'H': 'calm',         # happiness
    'W': 'disengaged'    # surprise (best approximation)
}

df["label"] = df["emotion"].map(mapping)
df.to_csv('shemo.csv', index=False)
df.head()

                                                path emotion       label
0  /kaggle/working/ser-india/data/raw/shemo_repo/...       A  frustrated
1  /kaggle/working/ser-india/data/raw/shemo_repo/...       N        calm
2  /kaggle/working/ser-india/data/raw/shemo_repo/...       N        calm
3  /kaggle/working/ser-india/data/raw/shemo_repo/...       H        calm
4  /kaggle/working/ser-india/data/raw/shemo_repo/...       N        calm

In [11]:
df = pd.read_csv("/kaggle/working/shemo.csv")   # ← change to your actual CSV path
print(df.head())
print(df.columns.tolist())
print(df['label'].value_counts())       # ← change 'label' to your actual column name if different
print(f"Total samples: {len(df)}")

                                                path emotion       label
0  /kaggle/working/ser-india/data/raw/shemo_repo/...       A  frustrated
1  /kaggle/working/ser-india/data/raw/shemo_repo/...       N        calm
2  /kaggle/working/ser-india/data/raw/shemo_repo/...       N        calm
3  /kaggle/working/ser-india/data/raw/shemo_repo/...       H        calm
4  /kaggle/working/ser-india/data/raw/shemo_repo/...       N        calm
['path', 'emotion', 'label']
label
calm          1229
frustrated    1059
disengaged     225
Name: count, dtype: int64
Total samples: 3000

In [12]:
LABEL2ID = {
    "calm":        0,
    "frustrated":  1,
    "disengaged":  2,
}
ID2LABEL = {v: k for k, v in LABEL2ID.items()}
NUM_LABELS = len(LABEL2ID)

print(LABEL2ID)
print(f"Number of classes: {NUM_LABELS}")

{'calm': 0, 'frustrated': 1, 'disengaged': 2}
Number of classes: 3

Phone audio augmentation

In [13]:
def simulate_phone_audio(audio: np.ndarray, sr: int = 16000) -> np.ndarray:
    # Codec compression: downsample to 8kHz then back
    degraded = librosa.resample(audio, orig_sr=sr, target_sr=8000)
    degraded = librosa.resample(degraded, orig_sr=8000, target_sr=sr)

    # Gaussian noise at ~12dB SNR
    signal_power = np.mean(degraded ** 2) + 1e-9
    noise_power  = signal_power / (10 ** (12 / 10))
    noise        = np.random.normal(0, np.sqrt(noise_power), len(degraded))
    degraded     = degraded + noise

    # Clip to safe range
    degraded = np.clip(degraded, -1.0, 1.0)
    return degraded.astype(np.float32)

print("Augmentation function ready")

Augmentation function ready

In [14]:
TARGET_SR      = 16000
MAX_SAMPLES    = TARGET_SR * 6   # 6 seconds max per clip

class ShemoDataset(Dataset):
    def __init__(self, df, processor, augment=False):
        self.df        = df.reset_index(drop=True)
        self.processor = processor
        self.augment   = augment

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row       = self.df.iloc[idx]
        file_path = row["path"]
        label     = LABEL2ID[row["label"]]

        # Load audio
        waveform, sr = torchaudio.load(file_path)

        # Mono
        if waveform.shape[0] > 1:
            waveform = waveform.mean(dim=0, keepdim=True)

        # Resample to 16kHz
        if sr != TARGET_SR:
            waveform = torchaudio.functional.resample(waveform, sr, TARGET_SR)

        audio = waveform.squeeze().numpy()

        # Truncate or pad to 6 seconds
        if len(audio) > MAX_SAMPLES:
            audio = audio[:MAX_SAMPLES]
        else:
            audio = np.pad(audio, (0, MAX_SAMPLES - len(audio)))

        # Phone degradation on training data only
        if self.augment:
            audio = simulate_phone_audio(audio)

        inputs = self.processor(
            audio,
            sampling_rate=TARGET_SR,
            return_tensors="pt",
            padding=True,
        )

        return {
            "input_values": inputs.input_values.squeeze(),
            "labels":       torch.tensor(label, dtype=torch.long),
        }

print("Dataset class ready")

Dataset class ready

In [16]:
MODEL_CKPT = "facebook/wav2vec2-base"

processor = Wav2Vec2Processor.from_pretrained(MODEL_CKPT)

model = Wav2Vec2ForSequenceClassification.from_pretrained(
    MODEL_CKPT,
    num_labels=NUM_LABELS,
    label2id=LABEL2ID,
    id2label=ID2LABEL,
    ignore_mismatched_sizes=True,
)

# Freeze feature extractor (renamed in transformers 4.40+)
for param in model.wav2vec2.feature_extractor.parameters():
    param.requires_grad = False

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
frozen    = sum(p.numel() for p in model.parameters() if not p.requires_grad)
print(f"Trainable params: {trainable:,}")
print(f"Frozen params:    {frozen:,}")
print("Model ready")

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.weight_proj.bias   | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
project_q.weight             | UNEXPECTED |
quantizer.codevectors        | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
projector.bias               | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Trainable params: 90,368,899
Frozen params:    4,200,448
Model ready

In [18]:
# Aggressive cleaning
df = df.dropna(subset=["path", "label"])
df = df[df["label"].isin(LABEL2ID.keys())]
df = df[df["path"].notna()]
df = df[df["path"] != ""]
df["label"] = df["label"].astype(str).str.strip()
df = df[df["label"].isin(LABEL2ID.keys())].reset_index(drop=True)

# Verify no NaN remains
print(f"NaN in label: {df['label'].isna().sum()}")
print(f"NaN in path:  {df['path'].isna().sum()}")
print(f"Clean samples: {len(df)}")
print(df["label"].value_counts())

NaN in label: 0
NaN in path:  0
Clean samples: 2513
label
calm          1229
frustrated    1059
disengaged     225
Name: count, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

train_df, val_df = train_test_split(
    df,
    test_size=0.15,
    stratify=df["label"],
    random_state=42,
)

print(f"Train: {len(train_df)}  |  Val: {len(val_df)}")
print("\nTrain distribution:")
print(train_df["label"].value_counts())

train_dataset = ShemoDataset(train_df, processor, augment=True)
val_dataset   = ShemoDataset(val_df,   processor, augment=False)

# Class weights to handle disengaged (225 samples) being underrepresented
classes = np.array(list(LABEL2ID.keys()))
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=train_df["label"].values,
)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).cuda()
print(f"\nClass weights: {dict(zip(LABEL2ID.keys(), class_weights.round(3)))}")
print("Datasets ready")

Train: 2136  |  Val: 377

Train distribution:
label
calm          1045
frustrated     900
disengaged     191
Name: count, dtype: int64

Class weights: {'calm': np.float64(0.681), 'frustrated': np.float64(0.791), 'disengaged': np.float64(3.728)}
Datasets ready

In [20]:
@dataclass
class DataCollatorForAudio:
    processor: Wav2Vec2Processor

    def __call__(self, features: List[Dict]) -> Dict[str, torch.Tensor]:
        input_values = [f["input_values"] for f in features]
        labels       = torch.tensor([f["labels"] for f in features], dtype=torch.long)

        batch = self.processor.pad(
            {"input_values": input_values},
            padding=True,
            return_tensors="pt",
        )
        batch["labels"] = labels
        return batch

data_collator = DataCollatorForAudio(processor=processor)

f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return f1_metric.compute(predictions=preds, references=labels, average="weighted")

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss = torch.nn.CrossEntropyLoss(weight=class_weights_tensor)(logits, labels)
        return (loss, outputs) if return_outputs else loss

print("Collator, metric, WeightedTrainer ready")

Downloading builder script: 0.00B [00:00, ?B/s]

Collator, metric, WeightedTrainer ready

In [21]:
OUTPUT_DIR = "/kaggle/working/wav2vec2-shemo-bfsi"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,

    num_train_epochs=10,
    learning_rate=3e-5,
    warmup_ratio=0.1,
    weight_decay=0.01,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    dataloader_num_workers=2,

    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,

    logging_steps=20,
    report_to="none",

    fp16=True,
    gradient_accumulation_steps=2,
)

print("Training arguments ready")

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training arguments ready

In [22]:
trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=340, training_loss=0.9120192078983083, metrics={'train_runtime': 1579.7903, 'train_samples_per_second': 13.521, 'train_steps_per_second': 0.215, 'total_flos': 1.16352072110592e+18, 'train_loss': 0.9120192078983083, 'epoch': 10.0})

In [43]:
OUTPUT_DIR = "/kaggle/working/wav2vec2-shemo-bfsi"
trainer.save_model(OUTPUT_DIR)
processor.save_pretrained(OUTPUT_DIR)
print("Model saved")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved

In [74]:
!zip -r my_model.zip /kaggle/working/wav2vec2-shemo-bfsi

  adding: kaggle/working/wav2vec2-shemo-bfsi/ (stored 0%)
  adding: kaggle/working/wav2vec2-shemo-bfsi/config.json (deflated 66%)
  adding: kaggle/working/wav2vec2-shemo-bfsi/processor_config.json (deflated 43%)
  adding: kaggle/working/wav2vec2-shemo-bfsi/tokenizer_config.json (deflated 73%)
  adding: kaggle/working/wav2vec2-shemo-bfsi/model.safetensors (deflated 9%)
  adding: kaggle/working/wav2vec2-shemo-bfsi/training_args.bin (deflated 53%)
  adding: kaggle/working/wav2vec2-shemo-bfsi/vocab.json (deflated 55%)

This Fine Tuning can be done better using IIITH Hindi Audio dataset combining with the Shemo one... For now we'll Go with the dataset we have now(SHEMO)